### ISSUE TITLE
Fix goroutine leak for eth client

### ISSUE THREAD

**Issue by b00ris** [autonity/autonity#389]
# Problem

Tests in the consensus/test package are highlighting goroutine leaks, which are currently ignored [here](https://github.com/clearmatics/autonity/blob/a72504639037c9d748c01cfaaee84d4a7e73acd3/consensus/test/testcase_test.go#L125).

We want to fix the source of the leaks, such that we don't see any occurring in our tests.

A stack trace of some leaks is provided below.
```
    leaks.go:78: found unexpected goroutines:
        [Goroutine 1998 in state select, with net/http.(*persistConn).writeLoop on top of the stack:
        goroutine 1998 [select]:
        net/http.(*persistConn).writeLoop(0xc05bc6cb40)
        	/usr/local/go/src/net/http/transport.go:1979 +0x113
        created by net/http.(*Transport).dialConn
        	/usr/local/go/src/net/http/transport.go:1361 +0xb1d
        
         Goroutine 1977 in state IO wait, with internal/poll.runtime_pollWait on top of the stack:
        goroutine 1977 [IO wait]:
        internal/poll.runtime_pollWait(0x6bae468, 0x72, 0xffffffffffffffff)
        	/usr/local/go/src/runtime/netpoll.go:182 +0x56
        internal/poll.(*pollDesc).wait(0xc05b86cd98, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
        	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
        internal/poll.(*pollDesc).waitRead(...)
        	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
        internal/poll.(*FD).Read(0xc05b86cd80, 0xc05beec000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1f2
        net.(*netFD).Read(0xc05b86cd80, 0xc05beec000, 0x1000, 0x1000, 0xc000044500, 0xc002979c40, 0x44f45fa)
        	/usr/local/go/src/net/fd_unix.go:202 +0x4f
        net.(*conn).Read(0xc002309c38, 0xc05beec000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        	/usr/local/go/src/net/net.go:177 +0x69
        net/http.(*connReader).Read(0xc05bc61ef0, 0xc05beec000, 0x1000, 0x1000, 0x1e256c1250, 0x57b4280, 0x72)
        	/usr/local/go/src/net/http/server.go:787 +0x107
        bufio.(*Reader).fill(0xc05bed01e0)
        	/usr/local/go/src/bufio/bufio.go:100 +0x10f
        bufio.(*Reader).Peek(0xc05bed01e0, 0x4, 0x1e256c1250, 0x57b4280, 0x0, 0x0, 0x57b4280)
        	/usr/local/go/src/bufio/bufio.go:138 +0x4f
        net/http.(*conn).serve(0xc05be0cdc0, 0x4f5c0c0, 0xc05bbd2900)
        	/usr/local/go/src/net/http/server.go:1903 +0x9bf
        created by net/http.(*Server).Serve
        	/usr/local/go/src/net/http/server.go:2884 +0x2f4
        
         Goroutine 1997 in state IO wait, with internal/poll.runtime_pollWait on top of the stack:
        goroutine 1997 [IO wait]:
        internal/poll.runtime_pollWait(0x6bae538, 0x72, 0xffffffffffffffff)
        	/usr/local/go/src/runtime/netpoll.go:182 +0x56
        internal/poll.(*pollDesc).wait(0xc05bd88598, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
        	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
        internal/poll.(*pollDesc).waitRead(...)
        	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
        internal/poll.(*FD).Read(0xc05bd88580, 0xc05bdb1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1f2
        net.(*netFD).Read(0xc05bd88580, 0xc05bdb1000, 0x1000, 0x1000, 0x1, 0x40325dc, 0xc00364fb88)
        	/usr/local/go/src/net/fd_unix.go:202 +0x4f
        net.(*conn).Read(0xc0001c5b20, 0xc05bdb1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        	/usr/local/go/src/net/net.go:177 +0x69
        net/http.(*persistConn).Read(0xc05bc6cb40, 0xc05bdb1000, 0x1000, 0x1000, 0xc00364fc88, 0x40079f5, 0xc05b8dbce0)
        	/usr/local/go/src/net/http/transport.go:1527 +0x7b
        bufio.(*Reader).fill(0xc05bd13b00)
        	/usr/local/go/src/bufio/bufio.go:100 +0x10f
        bufio.(*Reader).Peek(0xc05bd13b00, 0x1, 0x0, 0x0, 0x1, 0xc05c155700, 0x0)
        	/usr/local/go/src/bufio/bufio.go:138 +0x4f
        net/http.(*persistConn).readLoop(0xc05bc6cb40)
        	/usr/local/go/src/net/http/transport.go:1680 +0x1a3
        created by net/http.(*Transport).dialConn
        	/usr/local/go/src/net/http/transport.go:1360 +0xaf8
        ]
```

# Acceptance Criteria
Be able to successfully run the tests under `consensus/test` without ignoring any goroutine leaks.

**Comment by piersy** [comment]
@clearmatics/autonity This ticket is lacking any steps to recreate this leak, does anyone know what those steps might be or where this leak is originating from?

**Comment by piersy** [comment]
In order to complete the changes successfully I need to wait for upstream changes to be merged. Which will happen in #549

**Comment by yazzaoui** [comment]
Depreciated, closing.
