### ISSUE TITLE
Intermittent panic in TestTendermintStartStopFPlusTwoNodes

### ISSUE THREAD

**Issue by piersy** [autonity/autonity#624]
# Problem
The test fails intermittently and very rarely in this way, so far we have only seen it fail in the following run.
https://github.com/clearmatics/autonity/pull/623/checks?check_run_id=893465478

The failure log is below
```
ERROR[07-21|09:09:02.092] NewUnminedBlockEvent: old height unminedBlock addr=0x65dEdbae57a5BB4CaddB1A2f4da98196caD4C383 err="old height message"
ERROR[07-21|09:09:02.583] last mined block                         addr=0x7448D58eA926515F28f9E0D4f5831f0acd8f9013 idx=VC peer=VC num=5  hash="ea7fb5…63912e" txCount=6
ERROR[07-21|09:09:06.161] last mined block                         addr=0x8a653AE4DcD64eC5247bE1560C3a20e4C002cdc5 idx=VB peer=VB num=6  hash="ae5dc5…0e219a" txCount=6
ERROR[07-21|09:09:06.162] last mined block                         addr=0x65dEdbae57a5BB4CaddB1A2f4da98196caD4C383 idx=VE peer=VE num=6  hash="ae5dc5…0e219a" txCount=6
ERROR[07-21|09:09:06.173] last mined block                         addr=0xF8a654dAFBcA036944e6E735F5CbC63b43b90BE8 idx=VA peer=VA num=6  hash="ae5dc5…0e219a" txCount=6
ERROR[07-21|09:09:06.212] last mined block                         addr=0xF8a654dAFBcA036944e6E735F5CbC63b43b90BE8 idx=VA peer=VA num=7  hash="464c93…d4e64b" txCount=0
ERROR[07-21|09:09:06.212] last mined block                         addr=0x7B2F0A20FDDa2a185112928da2d03d6ce10eD789 idx=VD peer=VD num=5  hash="ea7fb5…63912e" txCount=6
ERROR[07-21|09:09:06.216] last mined block                         addr=0x8a653AE4DcD64eC5247bE1560C3a20e4C002cdc5 idx=VB peer=VB num=7  hash="464c93…d4e64b" txCount=0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x592fc8]

goroutine 82508 [running]:
math/big.(*Int).Add(0xc01082d280, 0xc0014dce78, 0x0, 0x20e72ceacd2f866a)
	/opt/hostedtoolcache/go/1.13.14/x64/src/math/big/int.go:118 +0x38
github.com/clearmatics/autonity/eth.(*ProtocolManager).BroadcastBlock(0xc00ced6000, 0xc00c906ea0, 0xc0166e4501)
	/home/runner/work/autonity/autonity/eth/handler.go:931 +0x2d4
created by github.com/clearmatics/autonity/eth/fetcher.(*BlockFetcher).insert.func1
	/home/runner/work/autonity/autonity/eth/fetcher/block_fetcher.go:686 +0xa50
FAIL	github.com/clearmatics/autonity/consensus/test	338.257s
```

Also seeing this on this run, different test `TestTendermintBusSuccess`

https://github.com/clearmatics/autonity/runs/906910645?check_suite_focus=true 

# Acceptance Criteria
Since we cannot reproduce this bug easily the PR must show how this occurred and make clear that this cannot happen again.

**Comment by Jason-Zhangxin-Chen** [comment]
This testcase is move to the new e2e test framework, thus it should be closed by: https://github.com/autonity/autonity/pull/950.

**Comment by lorenzo-dev1** [comment]
> This testcase is move to the new e2e test framework, thus it should be closed by: https://github.com/autonity/autonity/pull/950.

The PR has been merged and I cannot find the tests mentioned in the issue in our codebase anymore, therefore I am closing this as done. We can re-open if the panic happens again.

**Comment by lorenzo-dev1** [comment]
Re-opening, I actually found the test again, it is now called "TestResetRandomFPlusTwoNodes". Let's keep this issue open for some more time in case the panic can still happen.
