### ISSUE TITLE
Intermittent failure of TestAddIncorrectStakeholdersToList

### ISSUE THREAD

**Issue by piersy** [autonity/autonity#653]
# Problem
The following failure occurred in the following CI run.
https://github.com/clearmatics/autonity/runs/994847107?check_suite_focus=true
```
2020-08-17T17:50:53.1005054Z === RUN   TestAddIncorrectStakeholdersToList
2020-08-17T17:51:01.7396172Z VA === enode://3fcdd678b078111300cb36803eb6842acc79b4c952d45be1ced3c1a97463b6c92421aaf20c0f93ceffbe2bce7016bb3e993f543f069b565a9ead7ba003eb7305@127.0.0.1:42347?discport=0  -- 0xeA04D596Ca7eB11FD437b72F953297AE5e7f9159
2020-08-17T17:51:01.7397004Z VB === enode://e6863572fd7074a38c5af8909445e37baf56156882aa9a69099690a4011481cd5188bfdb6bc65e2564f0a54960575d1e3733b8f11c9d915aa4b6e06cc9cd6ee3@127.0.0.1:34049?discport=0  -- 0xB3199F0230e0cfcD3fF2718bEcB31F4D09d3EB95
2020-08-17T17:51:01.7398045Z VC === enode://735d0b13bf070dc801c51da463a568fc9f780375f187aaaf37bc4748b071f63fa6db309c3f17001e73768780ba5a3b4a76f87f4e566ccd38d69adba1a0a5cac7@127.0.0.1:44033?discport=0  -- 0xeF289243eb76CD27d4D334A7Bd4262457f1AEE3C
2020-08-17T17:51:01.7398808Z VD === enode://fdc73e8d81d968321fa79928360b87e0aead87b639c9af3c65a17d80e39be47e21beb92d739fab3786b9e41fb77d44e164f18afeb3882bee3f8a9e3319206902@127.0.0.1:44225?discport=0  -- 0x273ebd63C2D6C48A0dE4B1a5d050b0bA1866ab9a
2020-08-17T17:51:01.7399483Z VE === enode://3fb70ef0c43940422876c9b70e3c179f5a1b90ba46d211a89c09b8f907a178b30c626db227894269d3e61a8cddf067ce758ef7e32f85d1b5f20d557e53dd116d@127.0.0.1:42213?discport=0  -- 0x960129F20a1bEa61101dd7866614367a909B2754
2020-08-17T17:51:02.8104133Z Block 1 has 0 transactions
2020-08-17T17:51:02.8104490Z Block 2 has 1 transactions
2020-08-17T17:51:02.8106219Z Block 3 has 5 transactions
2020-08-17T17:51:02.8106932Z Block 4 has 6 transactions
2020-08-17T17:51:02.8107292Z Block 5 has 5 transactions
2020-08-17T17:51:02.8107550Z Block 6 has 4 transactions
2020-08-17T17:51:02.8107800Z Block 7 has 5 transactions
2020-08-17T17:51:02.8108775Z Block 8 has 5 transactions
2020-08-17T17:51:02.8109472Z Block 9 has 5 transactions
2020-08-17T17:51:02.8109766Z Block 10 has 8 transactions
2020-08-17T17:51:02.8110143Z Block 11 has 4 transactions
2020-08-17T17:51:02.8110404Z Block 12 has 2 transactions
2020-08-17T17:51:02.8110740Z Validator VD has 0 transactions
2020-08-17T17:51:02.8112007Z Validator VE has 0 transactions
2020-08-17T17:51:02.8112277Z Validator VA has 0 transactions
2020-08-17T17:51:02.8113503Z Validator VB has 0 transactions
2020-08-17T17:51:02.8113792Z Validator VC has 0 transactions
2020-08-17T17:51:02.8115642Z 
2020-08-17T17:51:02.8115883Z Transactions OK
2020-08-17T17:51:03.3227194Z panic: Failed to store the transaction index: leveldb: closed
2020-08-17T17:51:03.3233885Z 
2020-08-17T17:51:03.3234738Z goroutine 14221 [running]:
2020-08-17T17:51:03.3235187Z github.com/clearmatics/autonity/core/rawdb.WriteTxIndexTail(0x7f866679ac30, 0xc087b5aaa0, 0x0)
2020-08-17T17:51:03.3235583Z 	/home/runner/work/autonity/autonity/core/rawdb/accessors_chain.go:245 +0x13f
2020-08-17T17:51:03.3235976Z github.com/clearmatics/autonity/core.(*BlockChain).maintainTxIndex.func1(0x0, 0x16, 0xc07986d920)
2020-08-17T17:51:03.3236300Z 	/home/runner/work/autonity/autonity/core/blockchain.go:2276 +0x17d
2020-08-17T17:51:03.3236631Z created by github.com/clearmatics/autonity/core.(*BlockChain).maintainTxIndex
2020-08-17T17:51:03.3236945Z 	/home/runner/work/autonity/autonity/core/blockchain.go:2315 +0x2df
2020-08-17T17:51:03.3758956Z FAIL	github.com/clearmatics/autonity/consensus/test	20.486s
2020-08-17T17:51:03.3817456Z FAIL
2020-08-17T17:51:03.4632006Z ##[error]Process completed with exit code 1.
```

# Acceptance Criteria

Since this happens intermittently, it will be hard to verify the fix therefore the PR should make it clear what the problem was and how it has been fixed.

**Comment by aiman** [comment]
Even if this test is no longer valid, the underlying issue may be related to cleanup issues with the integration test framework.

**Comment by cmjc** [comment]
For test definition see  https://github.com/autonity/autonity/blob/cbb35664e27e034883aa3dfc77974d12347a9b6c/consensus/test/autonity_contract_test.go#L243

**Comment by Jason-Zhangxin-Chen** [comment]
Since the stake holder role is no longer valid for autonity protocol, and the regarding panic was due the the un-clean shutdown of the legacy test framework, I would close this issue by using PR: https://github.com/autonity/autonity/pull/950, as we replaced the legacy test framework with the new one.

**Comment by Jason-Zhangxin-Chen** [comment]
This test is now moved to the new e2e test framework in PR: https://github.com/autonity/autonity/pull/950
