### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by yazzaoui** [autonity/autonity#806]
Opening this issue to centralize issues we're having with flaky tests:

-  FAIL: TestQuorumPrevote/receive_quroum_prevote_for_proposal_block_when_in_step_>=_prevote (0.00s)

```
panic: invalid argument to Intn [recovered]
	panic: invalid argument to Intn

goroutine 149 [running]:
testing.tRunner.func1.2({0x993e00, 0xbdab30})
	/opt/hostedtoolcache/go/1.[20](https://github.com/autonity/autonity/actions/runs/5579173061/jobs/10194380373#step:5:21).5/x64/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:1529 +0x39f
panic({0x993e00, 0xbdab30})
	/opt/hostedtoolcache/go/1.20.5/x64/src/runtime/panic.go:884 +0x[21](https://github.com/autonity/autonity/actions/runs/5579173061/jobs/10194380373#step:5:22)3
math/rand.(*Rand).Intn(0xc990e6?, 0xc990e6?)
	/opt/hostedtoolcache/go/1.20.5/x64/src/math/rand/rand.go:179 +0x65
math/rand.Intn(...)
	/opt/hostedtoolcache/go/1.20.5/x64/src/math/rand/rand.go:358
github.com/autonity/autonity/consensus/tendermint/core.TestQuorumPrevote.func1(0x5c46f88ca79a792d?)
	/home/runner/work/autonity/autonity/consensus/tendermint/core/upon_condition_test.go:914 +0x1b5
testing.tRunner(0xc0001b[24](https://github.com/autonity/autonity/actions/runs/5579173061/jobs/10194380373#step:5:25)e0, 0xc00007a300)
	/opt/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.20.5/x64/src/testing/testing.go:16[29](https://github.com/autonity/autonity/actions/runs/5579173061/jobs/10194380373#step:5:30) +0x3ea
```

**Comment by Jason-Zhangxin-Chen** [comment]
> TestMultiSyncManyUselessWithLowTimeout

@lorenzo-dev1 About this flaky test, do you have any failed call trace or log context available?

**Comment by Jason-Zhangxin-Chen** [comment]
- "TestQuorumPrevote/receive_quroum_prevote_for_proposal_block_when_in_step_>=_prevote" was failed due to the input of rand.Intn() is `<=` `0`, it was fixed in the history. Now we let the input to be always greater than `0`.
- "TestACSystemOperatorOPs" was moved to the new test framework in PR: https://github.com/autonity/autonity/pull/950
- "TestOldProposal/receive_proposal_with_vr_>=_0_and_clients_is_lockedRound_>_vr_with_a_different_value" is fixed in PR: https://github.com/autonity/autonity/pull/950

**Comment by Jason-Zhangxin-Chen** [comment]
- Flaky test: "TestMultiSyncManyUselessWithLowTimeout" was fixed by PR: https://github.com/autonity/autonity/pull/950 in commit: https://github.com/autonity/autonity/pull/950/commits/2c65d23d9b7cbe720f811103bd1d408bf4a69730

**Comment by Jason-Zhangxin-Chen** [comment]
- Flaky test: " TestWalletNotifications" was fixed by PR: https://github.com/autonity/autonity/pull/950 in commit: https://github.com/autonity/autonity/pull/950/commits/ee3037f1f51f2488a5c88da93997d74eb98660ac

**Comment by lorenzo-dev1** [comment]
TestCollusionPVN is currently flaky in develop.
